// <auto-generated />
using System;
using HMB.GAP2019.Intranet.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HMB.GAP2019.Intranet.Data.Migrations
{
    [DbContext(typeof(IntranetContext))]
    [Migration("20210722142639_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Announcements.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHighPriority")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = @"##About
This is a markdown file. for more information about markdown please go to [this site](https://www.markdownguide.org/cheat-sheet)
",
                            EndDate = new DateTime(2020, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsHighPriority = true,
                            StartDate = new DateTime(2020, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to the Angular portion of the Grad Academy Project"
                        },
                        new
                        {
                            Id = 2,
                            Body = @"##Members
* Adam Smith
* Alicia Jeffers
* Brandon Tietz
* Colin Evans
* Jacqueline Ortiz
* Ptoli Whittington
",
                            EndDate = new DateTime(2020, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsHighPriority = false,
                            StartDate = new DateTime(2020, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Grad Academy Information"
                        },
                        new
                        {
                            Id = 3,
                            Body = @"##Project Breakdown
* Front end: [Angular](https://angular.io/)
* API: [ASP.NET Core 3.1 Web API](https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1)
* Database: [LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sqlallproducts-allversions)
",
                            EndDate = new DateTime(2020, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsHighPriority = true,
                            StartDate = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to the Grad Academy Presentation!"
                        });
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Authentication.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice.jones.admin@hmbnet.com",
                            FirstName = "Alice",
                            LastName = "Jones"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john.smith.employee@hmbnet.com",
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "pamela.rogers.pm@hmbnet.com",
                            FirstName = "Pamela",
                            LastName = "Rogers"
                        },
                        new
                        {
                            Id = 4,
                            Email = "carter.cruz.hr@hmbnet.com",
                            FirstName = "Carter",
                            LastName = "Cruz"
                        });
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Tasks.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsNoteRequired")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Timesheet.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Friday")
                        .HasColumnType("float");

                    b.Property<double>("Monday")
                        .HasColumnType("float");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<double>("Saturday")
                        .HasColumnType("float");

                    b.Property<double>("Sunday")
                        .HasColumnType("float");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<double>("Thursday")
                        .HasColumnType("float");

                    b.Property<int?>("TimeSheetId")
                        .HasColumnType("int");

                    b.Property<double>("Tuesday")
                        .HasColumnType("float");

                    b.Property<double>("Wednesday")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("TimeSheetId");

                    b.ToTable("TimeEntry");
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Timesheet.TimeSheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MondayOfWeek")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeSheet");
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Timesheet.TimeEntry", b =>
                {
                    b.HasOne("HMB.GAP2019.Intranet.Core.Tasks.Task", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HMB.GAP2019.Intranet.Core.Timesheet.TimeSheet", null)
                        .WithMany("Entries")
                        .HasForeignKey("TimeSheetId");
                });

            modelBuilder.Entity("HMB.GAP2019.Intranet.Core.Timesheet.TimeSheet", b =>
                {
                    b.HasOne("HMB.GAP2019.Intranet.Core.Authentication.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });
#pragma warning restore 612, 618
        }
    }
}
